import yaml from 'yaml';
import type { GithubWorkflow, WorkflowStep } from '../workflow-types';
import type { PackageManager } from '../../analyzer/types';

const GENERATED_HEADER = '# Generated by lovable-migrate — do not edit manually\n';

const YAML_OPTIONS = {
  lineWidth: 0,
  indent: 2,
} as const;

// ─── Serialization ────────────────────────────────────────────────────────────

export function serializeWorkflow(workflow: GithubWorkflow): string {
  return GENERATED_HEADER + yaml.stringify(workflow, YAML_OPTIONS);
}

// ─── Step builders ────────────────────────────────────────────────────────────

export function checkoutStep(): WorkflowStep {
  return { uses: 'actions/checkout@v4' };
}

export function setupNodeMatrixStep(pm: PackageManager): WorkflowStep {
  return {
    name: 'Set up Node.js ${{ matrix.node-version }}',
    uses: 'actions/setup-node@v4',
    with: {
      'node-version': '${{ matrix.node-version }}',
      cache: pm,
    },
  };
}

export function setupNodeReleaseStep(version: number, pm: PackageManager): WorkflowStep {
  return {
    name: 'Set up Node.js',
    uses: 'actions/setup-node@v4',
    with: {
      'node-version': version,
      'registry-url': 'https://registry.npmjs.org',
      cache: pm,
    },
  };
}

const INSTALL_CMD: Record<PackageManager, string> = {
  npm:  'npm ci',
  yarn: 'yarn install --frozen-lockfile',
  pnpm: 'pnpm install --frozen-lockfile',
  bun:  'bun install',
};

export function installStep(pm: PackageManager): WorkflowStep {
  return { name: 'Install dependencies', run: INSTALL_CMD[pm] };
}

const BUILD_CMD: Record<PackageManager, string> = {
  npm:  'npm run build',
  yarn: 'yarn build',
  pnpm: 'pnpm run build',
  bun:  'bun run build',
};

export function buildStep(pm: PackageManager): WorkflowStep {
  return { name: 'Build', run: BUILD_CMD[pm] };
}

const TEST_CMD: Record<PackageManager, string> = {
  npm:  'npm test',
  yarn: 'yarn test',
  pnpm: 'pnpm test',
  bun:  'bun test',
};

export function testStep(pm: PackageManager): WorkflowStep {
  return { name: 'Test', run: TEST_CMD[pm] };
}

export function publishDryRunStep(): WorkflowStep {
  return {
    name: 'Publish (dry-run)',
    run:  'npm publish --dry-run',
  };
}
