import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import path from 'path';
import fs from 'fs';
import type { ProjectContext } from '../../src/core/types';
import {
  runCicdPipeline,
  makeTempDir,
  removeTempDir,
} from '../helpers/pipeline';
import { normalizeOutput } from '../helpers/normalize';

// ─── Fatia 1 — contrato do módulo ────────────────────────────────────────────

describe('CICD — react-vite (contrato do módulo)', () => {
  let outputDir: string;
  let ctx: ProjectContext;

  beforeAll(async () => {
    outputDir = makeTempDir();
    ctx = await runCicdPipeline('react-vite', outputDir, true);
  });

  afterAll(() => removeTempDir(outputDir));

  it('cicd state está presente no contexto', () => {
    expect(ctx.cicd).toBeDefined();
  });

  it('readiness é ready', () => {
    expect(ctx.cicd!.readiness).toBe('ready');
  });

  it('ci summary está presente', () => {
    expect(ctx.cicd!.ci).toBeDefined();
    expect(Array.isArray(ctx.cicd!.ci.files)).toBe(true);
    expect(Array.isArray(ctx.cicd!.ci.issues)).toBe(true);
  });

  it('release summary está presente', () => {
    expect(ctx.cicd!.release).toBeDefined();
    expect(Array.isArray(ctx.cicd!.release.files)).toBe(true);
    expect(Array.isArray(ctx.cicd!.release.issues)).toBe(true);
  });

  it('projectName corresponde ao fixture', () => {
    expect(ctx.cicd!.projectName).toBe('react-vite');
  });

  it('fases anteriores do pipeline estão intactas', () => {
    expect(ctx.analysis).toBeDefined();
    expect(ctx.plan).toBeDefined();
    expect(ctx.validation).toBeDefined();
    expect(ctx.migration).toBeDefined();
    expect(ctx.deploy).toBeDefined();
  });
});

// ─── Fatia 2 — geração de workflows ──────────────────────────────────────────

describe('CICD — react-vite (geração de workflows)', () => {
  let outputDir: string;
  let ctx: ProjectContext;

  const ciPath      = () => path.join(outputDir, '.github/workflows/ci.yml');
  const releasePath = () => path.join(outputDir, '.github/workflows/release.yml');
  const read        = (p: string) => fs.readFileSync(p, 'utf-8').replace(/\r\n/g, '\n');

  beforeAll(async () => {
    outputDir = makeTempDir();
    ctx = await runCicdPipeline('react-vite', outputDir, true);
  });

  afterAll(() => removeTempDir(outputDir));

  // Existência dos arquivos
  it('gera .github/workflows/ci.yml no outputDir', () => {
    expect(fs.existsSync(ciPath())).toBe(true);
  });

  it('gera .github/workflows/release.yml no outputDir', () => {
    expect(fs.existsSync(releasePath())).toBe(true);
  });

  // ci.yml — invariantes
  it('ci.yml contém cabeçalho gerado', () => {
    expect(read(ciPath())).toContain('Generated by lovable-migrate');
  });

  it('ci.yml contém trigger push e pull_request no branch main', () => {
    const c = read(ciPath());
    expect(c).toContain('push:');
    expect(c).toContain('pull_request:');
    expect(c).toContain('main');
  });

  it('ci.yml contém matrix de node-version com 20 e 22', () => {
    const c = read(ciPath());
    expect(c).toContain('matrix:');
    expect(c).toContain('node-version:');
    expect(c).toContain('20');
    expect(c).toContain('22');
  });

  it('ci.yml usa npm cache', () => {
    const c = read(ciPath());
    expect(c).toContain('cache: npm');
  });

  it('ci.yml contém passos install e build (scripts presentes no fixture)', () => {
    const c = read(ciPath());
    expect(c).toContain('npm ci');
    expect(c).toContain('npm run build');
  });

  it('ci.yml omite step test quando fixture não tem script test', () => {
    // react-vite não tem scripts.test — gerador não deve incluir o step
    expect(read(ciPath())).not.toContain('npm test');
  });

  it('ci.yml usa actions/checkout e setup-node', () => {
    const c = read(ciPath());
    expect(c).toContain('actions/checkout');
    expect(c).toContain('actions/setup-node');
  });

  // release.yml — invariantes
  it('release.yml contém cabeçalho gerado', () => {
    expect(read(releasePath())).toContain('Generated by lovable-migrate');
  });

  it('release.yml contém trigger push em tags v*', () => {
    const c = read(releasePath());
    expect(c).toContain('tags:');
    expect(c).toContain('v*');
  });

  it('release.yml usa npm publish --dry-run (seguro por padrão)', () => {
    expect(read(releasePath())).toContain('npm publish --dry-run');
  });

  it('release.yml inclui registry-url para npm', () => {
    expect(read(releasePath())).toContain('registry.npmjs.org');
  });

  it('release.yml não contém referências ativas a secrets', () => {
    const c = read(releasePath());
    // Sem ${{ secrets.* }} — usuário configura manualmente quando quiser publicar de verdade
    expect(c).not.toContain('secrets.');
    expect(c).not.toContain('NPM_TOKEN');
  });

  // Snapshots — golden tests
  it('ci.yml corresponde ao snapshot', () => {
    expect(read(ciPath())).toMatchSnapshot();
  });

  it('release.yml corresponde ao snapshot', () => {
    expect(read(releasePath())).toMatchSnapshot();
  });

  it('estrutura do CicdState (invariantes) corresponde ao snapshot', () => {
    const { ci, release, readiness } = ctx.cicd!;
    const normalized = normalizeOutput({ ci, release, readiness }, { outputDir });
    expect(normalized).toMatchSnapshot();
  });
});
